# pypdfium2 ships no annotations; this declares only what the PDF parser uses.
class PdfiumError(RuntimeError):
    err_code: int | None

class PdfTextPage:
    def get_text_bounded(self) -> str: ...
    def close(self) -> None: ...

class PdfPage:
    def get_textpage(self) -> PdfTextPage: ...
    def close(self) -> None: ...

class PdfDocument:
    def __init__(self, input: bytes) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> PdfPage: ...
    def close(self) -> None: ...
